from __future__ import annotations

import argparse
import subprocess
from dataclasses import dataclass
from typing import Sequence


@dataclass
class ChangedFile:
    """Represents a single file discovered in a git diff."""

    path: str
    change_type: str


def is_git_repo() -> bool:
    """Check whether the current working directory is inside a git repository.

    Returns:
        True if the current directory is part of a git repository, otherwise False.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

    return result.stdout.strip() == "true"


def get_git_diff(staged: bool, compare: str | None, context: int) -> str:
    """Return the raw git diff string for the requested comparison mode.

    Args:
        staged: Whether to generate a diff from the staged index instead of unstaged changes.
        compare: Optional branch, tag, or commit to diff against.
        context: Number of surrounding context lines to include in the diff output.

    Returns:
        The raw diff text produced by git.
    """
    command = ["git", "diff", f"--unified={context}"]

    if compare:
        command.append(compare)
    elif staged:
        command.append("--cached")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def get_recent_commit_messages(limit: int) -> list[str]:
    """Return the most recent commit messages as one-line summaries.

    Args:
        limit: Number of recent commits to retrieve.

    Returns:
        A list of one-line commit message summaries, ordered from newest to oldest.
    """
    # TODO: Run a git log command that fetches the last `limit` commits in a one-line format.
    # TODO: Capture the command output, split it into lines, and return the resulting list.
    # TODO: Keep the subprocess handling simple and allow main() to surface failures.
    return []


def parse_changed_files(raw_diff: str) -> list[ChangedFile]:
    """Extract changed file metadata from raw git diff text.

    Args:
        raw_diff: The full raw diff output generated by git.

    Returns:
        A list of ChangedFile records describing each changed file and its change type.
    """
    # TODO: Scan the diff headers to identify each file touched by the diff.
    # TODO: Determine whether each file was modified, added, deleted, or renamed.
    # TODO: Normalize the extracted file path and change type into ChangedFile objects.
    return []


def assemble_review_prompt(
    commit_messages: Sequence[str],
    changed_files: Sequence[ChangedFile],
    raw_diff: str,
) -> str:
    """Compose the final code review prompt from git history and diff data.

    Args:
        commit_messages: Recent commit summaries to include for historical context.
        changed_files: Parsed list of changed files and their change types.
        raw_diff: Full raw diff text to embed in the prompt.

    Returns:
        A single formatted prompt string ready to print to stdout.
    """
    # TODO: Build a prompt with clear section headers and separators.
    # TODO: Include the sections in this order:
    # system instruction, recent commit history, changed file summary, full raw diff,
    # and a closing instruction asking for review on bugs, readability, and improvements.
    # TODO: Format the file summary and commit history so the prompt is easy to scan.
    return ""


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments for the diff-to-prompt tool.

    Args:
        argv: Optional explicit argument sequence. If omitted, argparse uses sys.argv.

    Returns:
        The parsed argparse namespace containing CLI option values.
    """
    # TODO: Keep the interface minimal and focused on selecting the diff source,
    # context line count, and number of commit summaries to include.
    parser = argparse.ArgumentParser(
        description="Format a git diff into a prompt for LLM-based code review."
    )
    parser.add_argument(
        "--staged",
        action="store_true",
        help="Use staged changes instead of unstaged working tree changes.",
    )
    parser.add_argument(
        "--compare",
        metavar="REF",
        help="Diff the current working tree against the given branch, tag, or commit.",
    )
    parser.add_argument(
        "--context",
        type=int,
        default=5,
        help="Number of surrounding context lines to include in the diff (default: 5).",
    )
    parser.add_argument(
        "--commits",
        type=int,
        default=10,
        help="Number of recent commit summaries to include (default: 10).",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Coordinate CLI parsing, git data collection, prompt assembly, and output.

    Args:
        argv: Optional explicit argument sequence. If omitted, argparse uses sys.argv.

    Returns:
        Process exit code, where 0 indicates success and non-zero indicates failure.
    """
    # TODO: Keep this function as the thin orchestration layer that wires together
    # argument parsing, git access, diff parsing, prompt assembly, and stdout output.
    args = parse_args(argv)

    if not is_git_repo():
        print("Not inside a git repository.")
        return 1

    try:
        raw_diff = get_git_diff(
            staged=args.staged,
            compare=args.compare,
            context=args.context,
        )
        commit_messages = get_recent_commit_messages(args.commits)
    except subprocess.CalledProcessError:
        # TODO: Replace this generic message with simple, user-friendly handling for
        # cases like an invalid compare target or other git command failures.
        print("Failed to run git commands.")
        return 1

    if not raw_diff.strip():
        print("No changes found.")
        return 0

    changed_files = parse_changed_files(raw_diff)
    prompt = assemble_review_prompt(
        commit_messages=commit_messages,
        changed_files=changed_files,
        raw_diff=raw_diff,
    )

    print(prompt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
