from __future__ import annotations

import argparse
import subprocess
from dataclasses import dataclass
from typing import Sequence


@dataclass
class ChangedFile:
    """Represents a single file discovered in a git diff."""

    path: str
    change_type: str


def is_git_repo() -> bool:
    """Check whether the current working directory is inside a git repository.

    Returns:
        True if the current directory is part of a git repository, otherwise False.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

    return result.stdout.strip() == "true"


def get_git_diff(staged: bool, compare: str | None, context: int) -> str:
    """Return the raw git diff string for the requested comparison mode.

    Args:
        staged: Whether to generate a diff from the staged index instead of unstaged changes.
        compare: Optional branch, tag, or commit to diff against.
        context: Number of surrounding context lines to include in the diff output.

    Returns:
        The raw diff text produced by git.
    """
    command = ["git", "diff", f"--unified={context}"]

    if compare:
        command.append(compare)
    elif staged:
        command.append("--cached")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def get_recent_commit_messages(limit: int) -> list[str]:
    """Return the most recent commit messages as one-line summaries.

    Args:
        limit: Number of recent commits to retrieve.

    Returns:
        A list of one-line commit message summaries, ordered from newest to oldest.
    """
    result = subprocess.run(
        ["git", "log", f"-n{limit}", "--oneline"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


def parse_changed_files(raw_diff: str) -> list[ChangedFile]:
    """Extract changed file metadata from raw git diff text.

    Args:
        raw_diff: The full raw diff output generated by git.

    Returns:
        A list of ChangedFile records describing each changed file and its change type.
    """
    changed_files: list[ChangedFile] = []
    current_path: str | None = None
    current_old_path: str | None = None
    current_change_type = "modified"

    for line in raw_diff.splitlines():
        if line.startswith("diff --git "):
            if current_path is not None:
                changed_files.append(
                    ChangedFile(path=current_path, change_type=current_change_type)
                )

            parts = line.split()
            old_path = parts[2][2:] if len(parts) > 2 else ""
            new_path = parts[3][2:] if len(parts) > 3 else ""

            current_old_path = old_path
            current_path = new_path
            current_change_type = "modified"
        elif line.startswith("new file mode "):
            current_change_type = "added"
        elif line.startswith("deleted file mode "):
            current_change_type = "deleted"
            current_path = current_old_path
        elif line.startswith("rename from "):
            current_change_type = "renamed"
        elif line.startswith("rename to "):
            current_path = line.removeprefix("rename to ")

    if current_path is not None:
        changed_files.append(ChangedFile(path=current_path, change_type=current_change_type))

    return changed_files


def assemble_review_prompt(
    commit_messages: Sequence[str],
    changed_files: Sequence[ChangedFile],
    raw_diff: str,
) -> str:
    """Compose the final code review prompt from git history and diff data.

    Args:
        commit_messages: Recent commit summaries to include for historical context.
        changed_files: Parsed list of changed files and their change types.
        raw_diff: Full raw diff text to embed in the prompt.

    Returns:
        A single formatted prompt string ready to print to stdout.
    """
    commit_history = "\n".join(f"- {message}" for message in commit_messages)
    if not commit_history:
        commit_history = "- No recent commits found."

    file_summary = "\n".join(
        f"- {changed_file.change_type}: {changed_file.path}"
        for changed_file in changed_files
    )
    if not file_summary:
        file_summary = "- No changed files detected."

    sections = [
        "You are an experienced code reviewer. Review the following git diff carefully and provide actionable feedback.",
        "=== RECENT COMMIT HISTORY ===",
        commit_history,
        "=== CHANGED FILES ===",
        file_summary,
        "=== FULL GIT DIFF ===",
        raw_diff,
        "Please review this change set for bugs, readability issues, maintainability concerns, and concrete improvements.",
    ]
    return "\n\n".join(sections)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments for the diff-to-prompt tool.

    Args:
        argv: Optional explicit argument sequence. If omitted, argparse uses sys.argv.

    Returns:
        The parsed argparse namespace containing CLI option values.
    """
    parser = argparse.ArgumentParser(
        description="Format a git diff into a prompt for LLM-based code review."
    )
    diff_source_group = parser.add_mutually_exclusive_group()
    diff_source_group.add_argument(
        "--staged",
        action="store_true",
        help="Use staged changes instead of unstaged working tree changes.",
    )
    diff_source_group.add_argument(
        "--compare",
        metavar="REF",
        help="Diff the current working tree against the given branch, tag, or commit.",
    )
    parser.add_argument(
        "--context",
        type=int,
        default=5,
        help="Number of surrounding context lines to include in the diff (default: 5).",
    )
    parser.add_argument(
        "--commits",
        type=int,
        default=10,
        help="Number of recent commit summaries to include (default: 10).",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Coordinate CLI parsing, git data collection, prompt assembly, and output.

    Args:
        argv: Optional explicit argument sequence. If omitted, argparse uses sys.argv.

    Returns:
        Process exit code, where 0 indicates success and non-zero indicates failure.
    """
    args = parse_args(argv)

    if not is_git_repo():
        print("Not inside a git repository.")
        return 1

    try:
        raw_diff = get_git_diff(
            staged=args.staged,
            compare=args.compare,
            context=args.context,
        )
        commit_messages = get_recent_commit_messages(args.commits)
    except subprocess.CalledProcessError as error:
        if args.compare:
            print(f"Branch or commit not found: {args.compare}")
        elif error.stderr.strip():
            print(error.stderr.strip())
        else:
            print("Failed to run git commands.")
        return 1
    except FileNotFoundError:
        print("Git is not installed or not available on PATH.")
        return 1

    if not raw_diff.strip():
        print("No changes found.")
        return 0

    changed_files = parse_changed_files(raw_diff)
    prompt = assemble_review_prompt(
        commit_messages=commit_messages,
        changed_files=changed_files,
        raw_diff=raw_diff,
    )

    print(prompt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
